# Default values for matomo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: matomo
  tag: 3.5.1-fpm-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - analytics.ietf.org
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

matomoNginx:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent

env:
  MATOMO_DATABASE_HOST: ""
  MATOMO_DATABASE_PORT: 3306
  MATOMO_DATABASE_ADAPTER: MYSQLI
  MATOMO_DATABASE_TABLES_PREFIX: matomo_
  MATOMO_DATABASE_USERNAME: matomo
  MATOMO_DATABASE_PASSWORD: matomo
  MATOMO_DATABASE_DBNAME: matomo
  MATOMO_DATABASE_ENABLE_SSL: 0
  MATOMO_DATABASE_SSL_KEY: ""
  MATOMO_DATABASE_SSL_CERT: ""
  MATOMO_DATABASE_SSL_CA: ""
  MATOMO_DATABASE_SSL_CIPHER: ""
  MATOMO_DATABASE_SSL_VERIFY_SERVER_CERT: 1
  MATOMO_DATABASE_PROXY_HOST: ""
  MATOMO_DATABASE_PROXY_PORT: ""
  MATOMO_DATABASE_PROXY_USERNAME: ""
  MATOMO_DATABASE_PROXY_PASSWORD: ""
  MATOMO_DATABASE_CONNECT_TIMEOUT: 60
  MATOMO_DATABASE_QUERY_TIMEOUT: 60
  MATOMO_DATABASE_CHARSET: utf8
  MATOMO_DATABASE_COLLATION: utf8_general_ci
  MATOMO_DATABASE_SOCKET: ""
  MATOMO_DATABASE_SSL_MODE: ""
  MATOMO_DATABASE_SSL: ""
  MATOMO_DATABASE_SSL_KEY_PATH: ""
  MATOMO_DATABASE_SSL_CERT_PATH: ""
  MATOMO_DATABASE_SSL_CA_PATH: ""
  MATOMO_DATABASE_SSL_CIPHER_PATH: ""
  MATOMO_DATABASE_SSL_VERIFY_SERVER_CERT_PATH: ""
  MATOMO_DATABASE_PROXY_HOST_PATH: ""
  MATOMO_DATABASE_PROXY_PORT_PATH: ""
  MATOMO_DATABASE_PROXY_USERNAME_PATH: ""
  MATOMO_DATABASE_PROXY_PASSWORD_PATH: ""
  MATOMO_DATABASE_CONNECT_TIMEOUT_PATH: ""
  MATOMO_DATABASE_QUERY_TIMEOUT_PATH: ""
  MATOMO_DATABASE_CHARSET_PATH: ""
  MATOMO_DATABASE_COLLATION_PATH: ""
  MATOMO_DATABASE_SOCKET_PATH: ""
  MATOMO_DATABASE_SSL_MODE_PATH: ""
  MATOMO_DATABASE_SSL_PATH: ""
  MATOMO_DATABASE_HOST_PATH: ""
  MATOMO_DATABASE_PORT_PATH: ""
  MATOMO_DATABASE_ADAPTER_PATH: ""
  MATOMO_DATABASE_TABLES_PREFIX_PATH: ""
  MATOMO_DATABASE_USERNAME_PATH: ""
  MATOMO_DATABASE_PASSWORD_PATH: ""
  MATOMO_DATABASE_DBNAME_PATH: ""
  MATOMO_DATABASE_ENABLE_SSL_PATH: ""
  MATOMO_DATABASE_SSL_KEY_PATH_PATH: ""
  MATOMO_DATABASE_SSL_CERT_PATH_PATH:
